AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  confirmation

  Sample SAM Template for confirmation
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ConfirmFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        Confirm:
          Type: Api
          Properties:
            Path: /confirm
            Method: post
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./confirm
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ConfirmApi:
    Description: "API Gateway endpoint URL for Prod stage for Confirm function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ConfirmFunction:
    Description: "Confirm Lambda Function ARN"
    Value: !GetAtt ConfirmFunction.Arn
  ConfirmFunctionIamRole:
    Description: "Implicit IAM Role created for Confirm function"
    Value: !GetAtt ConfirmFunctionRole.Arn
